# Generated by Django 2.0.6 on 2021-08-20 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('pk_sell', models.AutoField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(default='N/A', max_length=80)),
                ('date_buy', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pk_product', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='stock',
            fields=[
                ('pk_stock', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('fk_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Deportes.product')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='fk_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deportes.product'),
        ),
    ]
