# Generated by Django 2.0.6 on 2021-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='garment',
            fields=[
                ('pk_id_garment', models.AutoField(primary_key=True, serialize=False)),
                ('mark', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('discount', models.DecimalField(decimal_places=2, max_digits=3)),
                ('amount', models.IntegerField()),
                ('image', models.URLField(default='https://i.imgur.com/821M8H5.jpg')),
            ],
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('pk_id_mark', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
