# Generated by Django 2.0.6 on 2021-09-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0003_auto_20210901_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='price',
            field=models.IntegerField(),
        ),
    ]
