# Generated by Django 2.0.6 on 2021-09-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0004_auto_20210901_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garment',
            name='size',
            field=models.IntegerField(),
        ),
    ]
