# Generated by Django 2.0.6 on 2021-09-02 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0005_auto_20210901_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garment',
            name='size',
        ),
    ]
