# Generated by Django 2.0.6 on 2021-09-02 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deportes', '0006_remove_garment_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='garment',
            name='size',
            field=models.DateField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
